version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - app-network

  email-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email-service
    ports:
      - '3001:3001'
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
      EMAIL_USER: seu-email@gmail.com
      EMAIL_PASS: sua-senha
    depends_on:
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:
    external: true  # Altere para usar a mesma rede externa já criada
